// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lgrjtauxjfxmieuysidj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imxncmp0YXV4amZ4bWlldXlzaWRqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYyMTI3NzksImV4cCI6MjA2MTc4ODc3OX0.UutLFR9kiN6ANNAsr1UZDIlpa7kt6mYGCyr7yvRUE0c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);